sylius_admin:
    resource: '@SyliusAdminBundle/Resources/config/routing.yml'
    prefix: /admin

sylius_api:
    resource: '@SyliusAdminApiBundle/Resources/config/routing.yml'
    prefix: /api

sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"

sylius_import_export:
    resource: "@FOSSyliusImportExportPlugin/Resources/config/routing.yml"
    prefix: /admin

sylius_shop_payum:
    resource: '@SyliusShopBundle/Resources/config/routing/payum.yml'

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.xml'

bitbag_sylius_cms_plugin:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing.yml"

# sylius_shop:
#     resource: '@SyliusShopBundle/Resources/config/routing.yml'
#     prefix: /{_locale}
#     requirements:
#         _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

# sylius_shop_default_locale:
#     path: /
#     methods: [GET]
#     defaults:
#         _controller: sylius.controller.shop.locale_switch:switchAction